### ISSUE TITLE
Current time not displayed properly

### ISSUE THREAD

**Issue by trvrb** [mlandis/phylowood#13]
In the phylogeny, the root is properly annotated with the start time.  So, rabies says 1971.96 and has a tick mark above it.  However, the current time says 1971.96 when the slider is all the way to the left, not when the slider is aligned with the root of the tree.

**Comment by mlandis** [comment]
Fixed.

The root node is assigned a tiny branch so one can perform mask/highlight operations on the entire tree. The animation was retrieving the correct time, but the text field reporting the time didn't account for the root's tiny "false" branch.
