### ISSUE TITLE
Dragging slider directly results in display issues

### ISSUE THREAD

**Issue by trvrb** [mlandis/phylowood#14]
When dragging the phyloSlider line, rather than the handle, tracer lines in the continuous model display incorrectly and causes no updates to appear in discrete model.

**Comment by mlandis** [comment]
Fixed.

phyloSlider was returning continuous-valued clock ticks (through d3.scale.linear()), but these values are used as array indices. Also updated the phyloSlider drag() calls to use the new updateSlider code. Resolved with Math.round and checking for boundary conditions.
