### ISSUE TITLE
Switch polymaps to new map-tile server

### ISSUE THREAD

**Issue by mlandis** [mlandis/phylowood#23]
CloudMade will stop serving map tiles for free by May 1st. Need to switch to free service (Leaflet)?

**Comment by mlandis** [comment]
Mapbox gives 3000 maps/mo for free, 10000 maps/mo for $5/mo.
https://a.tiles.mapbox.com/v3/mlandis.hgp12886/page.html?secure=1#4/38.40/-122.82

OpenStreetMap gives unlimited maps/mo for free, but does not support custom maps.

Currently have Mapbox working w/ local Phylowood branch.

**Comment by trvrb** [comment]
That Mapbox map is lovely.

**Comment by mlandis** [comment]
Glad you like it. The geographical features help. 

I went ahead and pushed the Mapbox solution. When we break the 10000map/mo barrier, we can seek corporate sponsorship for an enterprise account.
